### ISSUE TITLE
EC2 생성 및 Java, Python 코드 작동 환경 구축

### ISSUE THREAD

**Issue by 724thomas** [CodeMentor-CodingSite/JavaServer#6]
## 🔨개발 할 기능
EC2 생성 및 Java, Python 코드 작동 환경 구축

## 🧩 세부 기능
해당 기능에 대한 세부 계획 작성 (ex. -[ ] 로그인 시 아이디 비번 입력 받기)
- [x] EC2 생성
- [x] Java, Python 코드 작동 환경 구축
- [x] Key파일 공유
- [x] Security 그룹 세팅

## 링크 프로젝트
이슈 등록전, 오른쪽 Projects에서 Backlog와 연결 시키기

## 📖 참고 사항
레퍼런스나 추가로 발생할 것으로 예상되는 이슈 작성 (ex. 아직 JWT 토큰 안만들어서 나중에 코드 추가해야함)

**Comment by hoonii2** [comment]
Java 코드 작동 관련

- [ ] Main, RealMain 객체 구분 생성 ( 실행을 위한 코드 생성 )
  - [ ] RealMain 내 Main 객체 인스턴스화 후 메서드 활용
  - [ ] test case -> 변수 생성 및 매개변수 전달, return 값 정답 여부 확인

- [ ] ec2 연결 및 폴더 생성 ( 실행 환경 구성 및 코드 전달 )
  - [ ] 코드 저장 여부 판단
    - [ ] 저장 시 Main.java, RealMain .java 를 모두 동일하게 사용하므로
      - [ ] "사용자명_문제번호" 등의 형식으로 폴더 생성
      - [ ] 저장공간 이슈 발생 가능성으로 S3 사용 고려
  - [ ] (optional) ssh or grpc 성능 테스트

- [ ] 코드 동작 관련
  - [ ] Timeout 처리 방법
    - [ ] Linux 스크립트 Timeout 설정
  - [ ] Memory 초과 처리 방법
    - [ ] java 실행 시 최대 메모리량 설정

**Comment by hoonii2** [comment]
1. 1차 정리 코드

echo 'public class RealMain {
    public static void main(String[] args) throws InterruptedException {
        Main main = new Main();

        [arg1 type] [arg1 name] = new [arg1 type][arg1 value];
        [arg2 type] [arg2 name] = [arg2 value];
        [answer type] [answer name] = [answer value];

        System.out.println(main.solution([arg1 name], [arg2 name]) == [answer name]);
    }
}

[사용자 입력 코드]' > RealMain.java && javac RealMain.java && java -Xmx[문제 요구 메모리 크기(단위:m)]m RealMain



2. 위 코드에서 요구되는 변수
  1) [arg1 type], [arg1 name], [arg1 value]
    ...
    [매개변수 수만큼]

  2) [answer type], [answer name], [answer value]

  3) [사용자 입력 코드]

  4) [문제 요구 메모리 크기 (단위:m)]



3. 필요 예외 처리

1. timeout
 -> Return : 
Killed

2. memory 초과
 -> Return : 
Error occurred during initialization of VM
Too small maximum heap
